### ISSUE TITLE
Incomplete Activation URL

### ISSUE THREAD

**Issue by uamv** [dav-is/flarum-ext-inviteonly#1]
When following the instruction [here](https://discuss.flarum.org/d/2141-problems-with-post-requests-when-using-cname-records/4) to set config URL to

`'url' => '//' . $_SERVER['HTTP_HOST'],`

the activation email is sent through containing an invalid URL (i.e. missing http: or https:).

**Edit:** It appears this may be a core thing, as I just found it is doing the same for the _Reset Password_ email message.

**Comment by dav-is** [comment]
I was going to say that my extension doesn't handle activation emails but it seemed you figured it out.

Although, I wouldn't call this an "issue" with core. It's more of a misconfiguration on your end.
